### ISSUE TITLE
libcdd not properly detected on 14.04.4 64 bits

### ISSUE THREAD

**Issue by olivier-stasse** [andreadelprete/robust-equilibrium-lib#1]
Hi Andrea,
Thanks for the great library.
I had problem in compiling the library on 14.04.04 LTS due to lack of 64 bits support.
Best,
Olivier.

**Comment by airobert** [comment]
I also have the same issue. Looks like it is trying to find the cmake file for CDD instead of using lcdd directly. We tried but now working.
Is there any other way to solve this problem or let it use the flag instead of finding the cmake file please?

Thanks!

**Comment by olivier-stasse** [comment]
IMHO, with a proper packaging through robotpkg we could use the macros in jrl-cmakemodules
to detect it properly. Should be quite fast to do.

**Comment by airobert** [comment]
So would you recommend me try this jrl-cmakemodules myself or wait until Andrea fix it? I am not familiar with jrl-cmakemodules.

**Comment by andreadelprete** [comment]
I've never packaged through robotpkg, but I'm willing to do it if Olivier feels like giving me some pointers. For the moment I specified in the installation instructions that you need to specify manually the paths to CDD and qpOases.

**Comment by airobert** [comment]
Dear all,

I managed to install it finally using user specified path as in the
instruction.
Thanks a lot!

PS: It would be nice of you if you can tell the user that we have to use
git clone --recursive ....

Robert

On 6 June 2016 at 09:51, Andrea Del Prete notifications@github.com wrote:

> I've never packaged through robotpkg, but I'm willing to do it if Olivier
> feels like giving me some pointers. For the moment I specified in the
> installation instructions that you need to specify manually the paths to
> CDD and qpOases.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/andreadelprete/robust-equilibrium-lib/issues/1#issuecomment-223890504,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACaalawQteOSoQ0M8OSrhWEd1PzMLshwks5qI9F9gaJpZM4ICE30
> .

## 

Cordialement/Regards,
Robert (Shuai Wang) @ LAAS-CNRS
https://airobert.github.io/

**Comment by andreadelprete** [comment]
Done
