### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by airobert** [andreadelprete/robust-equilibrium-lib#2]
Dear Andrea,

It would be nice of you if you can specify the installation steps. 
Also I found eigen can also be installed from 
sudo apt-get install libeigen3-dev
Maybe you can add that?

PS: I am not sure if we have to build qpOases from source. If so, could you please write that on the installation guide also? If not, maybe you can let us know in which package manager we can get it directly?

Thanks!

**Comment by andreadelprete** [comment]
Hi Robert! I added the installation steps. Hopefully you should find everything in there.
Andrea

**Comment by jmirabel** [comment]
For qpOases, you may prefer installing the pkg-config version we did for HPP: https://github.com/humanoid-path-planner/qpoases

**Comment by jmirabel** [comment]
If you do so, then, you just need the `ADD_REQUIRED_DEPENDENCY` of the jrl-cmakemodules

**Comment by andreadelprete** [comment]
I did it. Thank you @jmirabel for the tip!
